### ISSUE TITLE
请教依赖安装问题

### ISSUE THREAD

**Issue by GD2021** [yuxian158/check#10]
![image](https://user-images.githubusercontent.com/81171294/149668266-61e989c4-aa6a-4cc4-9cb9-4b54407a2693.png)
 提示这个怎么办？

**Comment by GD2021** [comment]
![image](https://user-images.githubusercontent.com/81171294/149668501-da64cf71-c836-4fa0-8229-56934f1b144e.png)
 请问这是什么错误？

**Comment by yuxian158** [comment]
漏cookie了，帮你删了，明天看看
