### ISSUE TITLE
python3 util.py 执行报错，依赖版本符合要求，但提示‘失败，请检查环境’

### ISSUE THREAD

**Issue by GordenMo** [yuxian158/check#13]
具体报错如下图
![image](https://user-images.githubusercontent.com/52969451/160389261-daed2dfa-c5e9-44dd-bc29-7e3fc9c8e0a5.png)

**Comment by yuxian158** [comment]
用的是青龙吗

**Comment by GordenMo** [comment]
一言惊醒梦中人，没进去青龙里面操作，进去青龙里面操作就正常了。
