### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Twshuai** [yuxian158/check#14]
![Screenshot_20220330_103412_mark.via.jpg](https://user-images.githubusercontent.com/99162051/160739451-505d2d5b-2c13-43a8-a797-49112d94bdee.jpg)运行哪个任务都说缺少脚本，但是宝塔文件里有文件

**Comment by yuxian158** [comment]
别的任务也不能吗

**Comment by Twshuai** [comment]
> 别的任务也不能吗

不行，都这样
用的最新版的青龙

**Comment by yuxian158** [comment]
@TwShuai 看一下别的任务的日志
