### ISSUE TITLE
天翼云盘跟acfun运行失败？

### ISSUE THREAD

**Issue by GD2021** [yuxian158/check#16]
![image](https://user-images.githubusercontent.com/81171294/172013848-95081505-d93e-4263-a41f-2002c56658d8.png)
![image](https://user-images.githubusercontent.com/81171294/172013875-5c48818c-6889-4607-82cb-9ef2cfd22689.png)
请教

**Comment by yuxian158** [comment]
@GD2021 acfun失效了，天翼云应该是风控了

**Comment by yuxian158** [comment]
等上游更新修复把
