### ISSUE TITLE
 cp: cannot stat '/ql/repo/yuxian158_check/check.sample.toml': No such file or directory 

### ISSUE THREAD

**Issue by cikichen** [yuxian158/check#17]
成功 当前环境为青龙面板v2.12- 继续执行  
未找到配置文件 
尝试移动配置文件到目录
 移动配置文件
 cp: cannot stat '/ql/repo/yuxian158_check/check.sample.toml': No such file or directory 
尝试修改定时时间

这个路径好像有问题
当前版本 2.13.3

**Comment by yuxian158** [comment]
是不是低版本升级上来的

**Comment by cikichen** [comment]
> 是不是低版本升级上来的

青龙面板是低版本升级的，脚本是新装

**Comment by yuxian158** [comment]
无解，重安面板吧，话说别的不会出现问题吗
