### ISSUE TITLE
青龙运行 日志显示这个错误时什么原因呢？

### ISSUE THREAD

**Issue by Rockwell2025** [yuxian158/check#5]
## 更新任务状态成功
Traceback (most recent call last):
  File "yuxian158_check_ck_acfun.py", line 5, in <module>
    from getENV import getENv
ModuleNotFoundError: No module named 'getENV'
## 执行结束... 2021-08-01 23:24:24  耗时 2 秒

**Comment by Rockwell2025** [comment]
没有通知，## 开始执行... 2021-08-02 19:30:11

## 更新任务状态成功


🔔腾讯视频会员签到, 开始!
## 更新任务状态成功

这个算成功吗

**Comment by yuxian158** [comment]
不算吧，第一个因为你没拉依赖，后面你是怎么搞了

**Comment by GD2021** [comment]
依赖是这个嘛？大佬
pip3 install requests rsa
ql repo https://github.com/yuxian158/check.git "ck_" "" "checksendNotify|getENV"
cp /ql/repo/yuxian158_check/config.json /ql/config/check.json

**Comment by GD2021** [comment]
docker exec -it ql/bin/sh

pip3 install requests
是安装这个嘛，大佬
